### ISSUE TITLE
Feature: Places Photos (thumbnail + header)

### ISSUE THREAD

**Issue by amanianai** [amanianai/covid-conscious#38]
Each Place needs to render photos: 
- **a thumbnail photo** (INDEX search results, and browsing pages (/home)
- **header photos** (Places SHOW view - 4, pulled from the Google Places API)

**Place Thumbnail Photos**
- [x] User Reviews (account/reviews/index)
- [x] User Bookmarks (account/bookmarks/index)
- [x] /home page (city page for a user)
- [x] Reviews new

**Place header photos**
- [x] Places SHOW view header

**Comment by friendlyantz** [comment]
Medium hard 2-3hrs

**Comment by friendlyantz** [comment]
done
