### ISSUE TITLE
Location header image

### ISSUE THREAD

**Issue by amanianai** [amanianai/covid-conscious#42]
Each location should have a header photo as shown below. 
- [ ] Ensure that a unique header photo can be populated for each city. Feel free to implement the fastest way possible :)

![Screen Shot 2020-12-09 at 12 34 23 AM](https://user-images.githubusercontent.com/39270434/101593863-4aff2b80-39b6-11eb-9039-34687744ae07.png)

**Comment by friendlyantz** [comment]
![image](https://user-images.githubusercontent.com/70934030/101763185-8b83b400-3b32-11eb-98f0-5c30b16ca839.png)
![image](https://user-images.githubusercontent.com/70934030/101763215-976f7600-3b32-11eb-94da-1a9b71ab870b.png)

- [ ] done
