### ISSUE TITLE
Hookup: Overall Scores Chart

### ISSUE THREAD

**Issue by amanianai** [amanianai/covid-conscious#54]
The chart should display the distribution of COVID Scores for a place.

For each progress bar, we want to pass a % out of the total number of reviews. For example, the first bar for excellent will be passed the % representing (no. of reviews with a score above 9 / total number of reviews).

Excellent (9-10)
Very Good (8)
Average (6-7)
Poor (3-5)
Terrible (0-2)

![Screen Shot 2020-12-09 at 3 09 39 AM](https://user-images.githubusercontent.com/39270434/101608941-fc5c8c00-39cb-11eb-8b5b-180fce123be6.png)

![Screen Shot 2020-12-09 at 3 15 01 AM](https://user-images.githubusercontent.com/39270434/101609568-bb18ac00-39cc-11eb-85d0-23939f3819a8.png)

**Comment by friendlyantz** [comment]
Easy, 1hr job

**Comment by rycmak** [comment]
> Easy, 1hr job

No, 5 minutes ;-).
