### ISSUE TITLE
Reviews: Change Answer Options to yes/no + add COVID protcols

### ISSUE THREAD

**Issue by amanianai** [amanianai/covid-conscious#57]
For these questions, please change the options to be yes and no either as an ENUM or BOOLEAN. This will be much easier to style and render on the frontend and also to calculate for the score.

Should be a yes/no question:
- :hand_sanitizer
-:temperature_checks
- :social_distancing
- :contract_tracing
- face_mask

Please also add covid_protocols to the database with the same ENUM or BOOLEAN answer options of "yes"/"no"
**Add to database**
- [ ] covid_protocols

![Screen Shot 2020-12-09 at 3 17 31 AM](https://user-images.githubusercontent.com/39270434/101609859-164a9e80-39cd-11eb-8a92-90d8b18159cb.png)

The user will be selecting "yes" or "no" on the review/new. No edits are needed on the frontend unless they are part of changing how the options render. Styling will be added once the backend change is made. :)

![Screen Shot 2020-12-09 at 3 24 47 AM](https://user-images.githubusercontent.com/39270434/101610607-17c89680-39ce-11eb-92c4-0767466cd7c3.png)

**Comment by friendlyantz** [comment]
Easy-med job 1-2hrs
