### ISSUE TITLE
Add website link to Place show header

### ISSUE THREAD

**Issue by amanianai** [amanianai/covid-conscious#61]
![Screen Shot 2020-12-09 at 3 43 28 AM](https://user-images.githubusercontent.com/39270434/101612838-b524ca00-39d0-11eb-9811-ba5c26dc191c.png)

**Comment by friendlyantz** [comment]
- [ ] ![image](https://user-images.githubusercontent.com/70934030/101765016-da324d80-3b34-11eb-8e50-d0a298e070e1.png)
